[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gaussFitSpec"
version = "1.0.1"
description = "Lightweight 1D Gaussian spectral decomposition."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
  { name = "Hongxing Chen" }
]
dependencies = [
  "matplotlib>=3.7",
  "numpy>=1.24",
  "pandas>=2.0",
  "scipy>=1.10"
]

[project.optional-dependencies]
dev = [
  "pytest>=7.4"
]
docs = [
  "sphinx>=8",
  "sphinx-rtd-theme>=3"
]

[tool.setuptools]
package-dir = { "" = "src" }
license-files = ["LICENSE"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
